version: "3.8"

services:
    thermostat:
        image: mobylab/ac-device:lab3
        ports:
            - 5000:5000
        environment:
            D_NAME: "thermostat"
            D_TYPE: 3
            D_DESC: "This is a thermostat"
            S_METRIC: "temperature"
            S_UNIT: "degrees Celsius"
            S_MIN: 10
            S_MAX: 25
            S_STEP: 0.5
            S_INT: 1
            A_UNIT: "degrees Celsius"
            A_BIN: 0
            A_MIN: 10
            A_MAX: 25

    smart_light:
        image: mobylab/ac-device:lab3
        ports:
            - 5001:5000
        environment:
            D_NAME: "smart_light"
            D_TYPE: 2
            D_DESC: "This is a smart light"
            A_UNIT: "N/A"
            A_BIN: 1
            A_STATE0: "off"
            A_STATE1: "on"