global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'server'
    static_configs:
      - targets: ['server:8000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']